sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456sjn
  aliyun:
    oss:
      endpoint: https://oss-cn-beijing.aliyuncs.com
      bucketName: ning-restaurant
  redis:
    host: localhost
    port: 6379
    database: 0 # 默认使用0号数据库
    # 没有密码，不配置 password
  wechat1:
    appid: wx58502940b2c06581
    secret: a239d112e0270f41562c6004a262d2d1
  mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml # 如果使用 XML 映射文件
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启 SQL 日志
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual