---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lenovo.
--- DateTime: 2024/12/16 16:10
---
-- 1. 参数列表
-- 1.1 优惠券ID
local voucherId = ARGV[1]
-- 1.2 用户ID
local userId = ARGV[2]
-- 1.3 订单ID
local orderId = ARGV[3]
-- 2. 数据key
-- 2.1 库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 2.2 订单key
local orderKey = 'seckill:order:' .. voucherId
-- 3. 判断逻辑业务
-- 3.1 超卖：判断库存是否充足 get StockKey
local stock = redis.call('get', stockKey)
--redis.call('set', 'debug:stockKey_check', 'StockKey is: ' .. stockKey)
if (stock == false or tonumber(stock) <= 0) then
    -- 3.2 库存不存在或不足则返回1
    --redis.call('set', 'debug:stock_check', 'Stock is: ' .. tostring(tonumber(stock)))
    return 1
end
-- 3.2 一人一单：根据订单key判断用户是否下过单
if (redis.call('sismember', orderKey, userId) == 1) then
    -- 3.3 存在下过单，说明是重复下单，返回2
    return 2
end
-- 4.执行逻辑
-- 4.1 扣库存
redis.call('incrby', stockKey, -1)
-- 4.2 下单（保存用户：订单key - 用户ID)
redis.call('sadd', orderKey, userId);
-- 4.3 发送到消息队列  XADD stream.orders * k1 v1 k2 v2 k3 v3 ...
--redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0;